---
driver:
  name: docker
  hostname: kibana.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: kibana
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - kibana
  pillars:
    top.sls:
      base:
        "*":
          - kibana
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux.git

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: kibana_server
    provisioner:
      pillars-from-files:
        kibana.sls: tests/pillar/kibana_server.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
